---
apiVersion: v1
kind: Service
metadata:
  name: service-p9-dashboard-staging
spec:
  type: NodePort
  ports:
    - name: service-p9-dashboard-staging
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: p9-dashboard-staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p9-dashboard-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p9-dashboard-staging
  template:
    metadata:
      labels:
        app: p9-dashboard-staging
    spec:
      containers:
        - name: p9-dashboard-staging
          image: gcr.io/agile-infinity-329404/p9-dashboard:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
            initialDelaySeconds: 5
          env:
            - name: PORT
              value: '80'
