export const SET_GLOBAL = 'SET_GLOBAL';
export const SET_GLOBAL_INTERNET = 'SET_GLOBAL_INTERNET';
export const SET_GLOBAL_SETTINGS = 'SET_GLOBAL_SETTINGS';
export const SET_GLOBAL_OPTIONS = 'SET_GLOBAL_OPTIONS';
export const SET_GLOBAL_NOTIFICATIONS = 'SET_GLOBAL_NOTIFICATIONS';
